name: CI

on:
  push:
    branches: [main, ci-cd]
  pull_request:
    branches: [main, ci-cd]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Lint frontend and backend
        run: npm run lint --workspace=apps/frontend

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Type check all
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Build frontend
        run: npm run build --workspace=apps/frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: false
          tags: music-track-frontend:ci
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: apps/frontend/dist

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run frontend unit tests
        run: npm run test:ci --workspace=apps/frontend -- test/unit/